App\Entities\Post:
    type: entity
    table: posts
    repositoryClass: App\Repositories\PostRepository
    id:
      id:
          type: integer
          generator:
              strategy: auto
          options:
              unsigned: true

    fields:
      title:
        type: string
        length: 255

      isActive:
        type: boolean

      createdAt:
        type: datetime

      updatedAt:
        type: datetime

    manyToOne:
      user:
        targetEntity: App\Entities\User

    manyToMany:
      categories:
          targetEntity: App\Entities\Category
          cascade: [ 'persist' ]
          fetch: EXTRA_LAZY
          joinTable:
              name: post_categories