App\Entities\BookAudio:
        type: entity
        table: book_audio
        repositoryClass: App\Repositories\BookAudioRepository

        id:
          id:
            type: integer
            generator:
                strategy: auto
            options:
                unsigned: true
        fields:
            name:
              type: string
              length: 255

            length:
              type: integer
              comment: 'by seconds'
              nullable: true

            body:
              type: text

            chapter:
              type: integer

            isActive:
              type: boolean

            status:
              type: integer
              length: 1

            fileSource:
              type: string

            steemSlug:
              type: string
              length: 255
              nullable: true

            modComment:
              type: text
              nullable: true

            createdAt:
              type: datetime

            updatedAt:
              type: datetime
              nullable: true

        manyToOne:
            user:
              targetEntity: App\Entities\User
            book:
              targetEntity: App\Entities\Book

        manyToMany:
            tags:
                targetEntity: App\Entities\AudioTags
                cascade: [ 'persist' ]
                fetch: EXTRA_LAZY
                indexBy: type
                joinTable:
                    name: book_audio_tags
