App\Entities\Book:
      type: entity
      table: books
      repositoryClass: App\Repositories\BookRepository

      indexes:
        book_language:
            columns: ["language"]
        year:
            columns: ["year"]
        book_name:
            columns: ['name']
            flags: fulltext
      id:
        id:
            type: integer
            generator:
                strategy: auto
            options:
                unsigned: true
      fields:
        name:
            type: string
            length: 255
        description:
            type: text
        isbn:
            type: string
            length: 255
        year:
            type: string
            length: 4
        page:
            type: integer
        cover:
            type: string
            lenght: 255
        language:
            type: string

        releaseDate:
            type: datetime

      oneToOne:
        post:
          targetEntity: App\Entities\Post
          cascade: [ 'persist' ]

      manyToOne:
        author:
          targetEntity: App\Entities\Author
          cascade: [ 'persist' ]
          fetch: EAGER