App\Entities\BookAudio:
        type: entity
        table: book_audio
        repositoryClass: App\Repositories\BookAudioRepository

        id:
          id:
            type: integer
            generator:
                strategy: auto
            options:
                unsigned: true
        fields:
            name:
              type: string
              length: 255

            length:
              type: integer
              comment: 'by seconds'
              nullable: true

            language:
              type: string
              length: 4

            body:
              type: text

            fileSource:
              type: string

            createdAt:
              type: datetime

            updatedAt:
              type: datetime
              nullable: true

        manyToOne:
            user:
              targetEntity: App\Entities\User
            book:
              targetEntity: App\Entities\Book
