App\Entities\User:
    type: entity
    table: users
    repositoryClass: App\Repositories\UserRepository

    uniqueConstraints:
        uniq_users_account:
            columns: [ account ]
        uniq_users_uuid:
            columns: [ uuid ]

    indexes:
        account_fulltext:
            columns: ["account"]
            flags: fulltext
        idx_users_active:
            columns: [ is_active ]

    id:
        id:
            type: integer
            generator:
                strategy: auto
            options:
                unsigned: true

    fields:
        uuid:
            type: guid

        isActive:
            type: boolean

        name:
            type: string
            length: 255

        accessToken:
            type: text
            length: 65535
            nullable: true

        refreshToken:
            type: text
            length: 65535
            nullable: true

        rememberToken:
            type: string
            length: 100
            nullable: true

        account:
            type: string
            length: 60
            unique: true

        profileImage:
            type: string
            length: 255
            nullable: TRUE

        lastLogin:
            type: datetime
            nullable: true

        createdBy:
            type: string
            length: 36

        updatedBy:
            type: string
            length: 36

        createdAt:
            type: datetime

        updatedAt:
            type: datetime


    manyToMany:
        addresses:
            targetEntity: App\Entities\Address
            cascade: [ 'persist' ]
            fetch: EXTRA_LAZY
            indexBy: type
            joinTable:
                name: user_addresses

        roles:
            targetEntity: App\Entities\Role
            cascade: [ 'persist' ]
            fetch: EXTRA_LAZY
            orderBy: { name: 'ASC' }
            joinTable:
                name: user_roles

        permissions:
            targetEntity: App\Entities\Permission
            cascade: [ 'persist' ]
            fetch: EXTRA_LAZY
            joinTable:
                name: user_permissions

        organizations:
            targetEntity: App\Entities\Organization
            inversedBy: users
            cascade: [ 'persist' ]
            fetch: EXTRA_LAZY
            orderBy: { name: 'ASC' }
            joinTable:
                name: user_organizations
